[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]

remappings = [
  "forge-std/=node_modules/forge-std/src",
  "ds-test/=node_modules/ds-test/src",
  "src/=src",
  "test/=test",
  "core/=../core"
]

allow_paths = ["../core"]

solc_version = "0.8.24"

[fmt]
bracket_spacing = true
number_underscore = "thousands"
