engine-jwt-file="jwt.toml"



snapshot-interval=999

[state]
persist-interval=99

[tracing]
endpoint="http://tracing.com"
headers="Authorization=Basic 123456"

[xchain]
[xchain.evm-rpc-endpoints]
ethereum = "http://ethereum.rpc"
optimism = "http://optimism.rpc"
