[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]

remappings = [
  "forge-std/=node_modules/forge-std/src",
  "src/=src",
  "test/=test",
  "core/=../core"
]

allow_paths = ["../core"]
ffi = true

solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
gas_limit = 1000000000000000000
# gas_limit = 18446744073709551615

[fmt]
bracket_spacing = true
number_underscore = "thousands"
