network = "devnet"
anvil_chains = ["mock_l2", "mock_l1"]

multi_omni_evms = true
pingpong_n = 5 # Increased ping pong to span validator updates
evidence = 1 # Slash a validator for double signing
all_e2e_tests = true

[node.validator01]
[node.validator02]
[node.validator03]
[node.validator04]
start_at = 20
state_sync = true

[node.fullnode01]
mode = "full"
perturb = ["restart"]

# Trigger validator updates at height 10
[validator_update.10]
fullnode01 = 100 # Add fullnode01 as validator by depositing 100 ether $OMNI (the minimum deposit)

# Additional perturbations.
[perturb]
validator02_evm = ["stopstart"]
relayer = ["restart"]
validator03 = ["rollback"]

[node.fullnode02]
mode = "archive"
