network = "devnet"
anvil_chains = ["mock_l2", "mock_l1"]

pingpong_n = 6 # Increased ping pong to span forks

[node.validator01]
[node.validator02]
[node.validator03]
[node.validator04]

[perturb]
mock_l1 = ["fuzzyhead_dropmsgs","fuzzyhead_dropblocks","fuzzyhead_attroot","fuzzyhead_moremsgs"]


[node.fullnode01]
mode = "archive"
