network = "omega"
public_chains = ["holesky","op_sepolia", "base_sepolia","arb_sepolia"]

multi_omni_evms = true
prometheus = true

[node.validator01]
[node.validator02]
[node.validator03]
[node.validator04]

[node.seed01]
mode = "seed"
[node.seed02]
mode = "seed"

[node.fullnode01]
mode = "full"
[node.fullnode02]
mode = "full"
[node.fullnode03]
mode = "full"
[node.fullnode04]
mode = "full"
[node.fullnode05]
mode = "full"

[node.archive01]
mode = "archive"
[node.archive02]
mode = "archive"


[keys.validator01]
validator = "0xCE624ce5C5717b63CED36AfB76857183E0a8a6eb"

[keys.validator02]
validator = "0x98Eb13371c095905985cddE937018881d4D7f229"

[keys.validator03]
validator = "0xe96cF9Ad91cD6dc911817603Dfb3c65d5f532B95"

[keys.validator04]
validator = "0xdBd26a685DB4475b6c58ADEC0DE06c6eE387EAa8"

[keys.seed01]
p2p_consensus = "623AB30714ECFC8A0C0DA0227A1B5BD9CF5B3D8B"

[keys.seed01_evm]
p2p_execution = "0x4480E59696A840a4A1CFf5Ca20cB925de152a024"

[keys.seed02]
p2p_consensus = "7582E893545ECDC8D43402198CCB9100584973B6"

[keys.seed02_evm]
p2p_execution = "0x492dA9a43ADD943A5359bF83CCD2d3Fd4235b870"
