network = "omega"
public_chains = ["op_sepolia", "base_sepolia","arb_sepolia"]

multi_omni_evms = true
prometheus = true

pinned_halo_tag = "883cc00" # disable holesky
pinned_relayer_tag = "883cc00"
pinned_monitor_tag = "883cc00"
pinned_solver_tag = "883cc00"

[node.validator01]
[node.validator02]
[node.validator03]
[node.validator04]

[node.seed01]
mode = "seed"
[node.seed02]
mode = "seed"

[node.fullnode01]
mode = "full"
[node.fullnode02]
mode = "full"

[node.archive01]
mode = "archive"
[node.archive02]
mode = "archive"

# Validator Keys
[keys.validator01]
validator = "0xCE624ce5C5717b63CED36AfB76857183E0a8a6eb"
p2p_consensus = "949145F115F83488A91179D51D7D3BAB5AE6B244"
[keys.validator01_evm]
p2p_execution = "0x243499570DabEFA3e51f66eb670293498525504A"
[keys.validator02]
validator = "0x98Eb13371c095905985cddE937018881d4D7f229"
p2p_consensus = "F3CC7B678464BD2271E909BD7151B6538B9BD1DE"
[keys.validator02_evm]
p2p_execution = "0x73b857e0Cf1bD85C9c45c9CAaa727c0b8bcf8Dcf"
[keys.validator03]
validator = "0xe96cF9Ad91cD6dc911817603Dfb3c65d5f532B95"
p2p_consensus = "2FA6ACCE36ECE9E6520424CE80D77746FA8994FC"
[keys.validator03_evm]
p2p_execution = "0x238C8B4C109f92B145f821f653E5c3F823B7eB02"
[keys.validator04]
validator = "0xdBd26a685DB4475b6c58ADEC0DE06c6eE387EAa8"
p2p_consensus = "811E42EE1131DDF07BA139269BF541917261DD7C"
[keys.validator04_evm]
p2p_execution = "0x04DC956cDe2F3311f5492B582d86e53DCc59BF9e"

# Seed keys
[keys.seed01]
p2p_consensus = "623AB30714ECFC8A0C0DA0227A1B5BD9CF5B3D8B"
[keys.seed01_evm]
p2p_execution = "0x4480E59696A840a4A1CFf5Ca20cB925de152a024"
[keys.seed02]
p2p_consensus = "7582E893545ECDC8D43402198CCB9100584973B6"
[keys.seed02_evm]
p2p_execution = "0x492dA9a43ADD943A5359bF83CCD2d3Fd4235b870"

# Archive keys
[keys.archive01]
p2p_consensus = "2320703BF5434BBC4B1050A90F0FBF842D4878F9"
[keys.archive01_evm]
p2p_execution = "0x33194570113B14FFD00b9E53cf2e405Bc62C2a5E"
[keys.archive02]
p2p_consensus = "1AFC3479B2A16BCA9DA5BEC7BFF750A7B5FFE53D"
[keys.archive02_evm]
p2p_execution = "0xd9B2Ca2215f5a04C1BbaAb8379A37cE21C025AE8"

# Fullnode keys
[keys.fullnode01]
p2p_consensus = "AD9C13930160CE5A452794D6C73E1F9C38FDBC16"
[keys.fullnode01_evm]
p2p_execution = "0xa22ae699EE8b08FF30F6dE68dAAF73Ed97A77F59"
[keys.fullnode02]
p2p_consensus = "15EB1CD69EFA8260F613C8D0F59CBEE7A109DBB9"
[keys.fullnode02_evm]
p2p_execution = "0x82C7b4316cB494548CDe0bdaAEC530E0bdEb85Ab"
