network = "staging"
public_chains = ["op_sepolia","base_sepolia","arb_sepolia"]
anvil_chains = ["slow_l1"]
multi_omni_evms = true
prometheus = true

[node.validator01]
[node.validator02]

[node.seed01]
mode = "seed"

[node.fullnode01]
mode = "archive"

[keys.validator01]
validator = "0xD6CD71dF91a6886f69761826A9C4D123178A8d9D"
p2p_consensus = "324F0A865DB7EAFBF53A387FC74E58169EDFA6C4"

[keys.validator01_evm]
p2p_execution = "0x86e640Ac9c8c693BBFFd2E31f91522b95c1274BF"

[keys.validator02]
validator = "0x9C7bf21f72CA34af89F620D27E0F18C4366b88c6"
p2p_consensus = "9BC8F7A673BBE3AB56B18D9753C823166B0FE16C"

[keys.validator02_evm]
p2p_execution = "0x6f19842a7B88724c715Cc7e8959Ab3A5172ad142"

[keys.seed01]
p2p_consensus = "4B2D413D49F0549694DC2522B1CBD367B61A3411"

[keys.seed01_evm]
p2p_execution = "0x657D5AB16fe5A8fE9979eF5eCfB533AB3B6FbaCa"

[keys.fullnode01]
p2p_consensus = "B0B2F907C12D79D0D74973FAF8BBC4F5435A8E86"

[keys.fullnode01_evm]
p2p_execution = "0xFB2BA51eEe9A745fE8B87F82C1A46527C7c6108f"
