name: check solidity artifacts

on:
  workflow_call:

jobs:
  check_sol_artifacts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'v1.24'
      - name: Install Foundry
        uses: ./.github/actions/setup-foundry
      - name: Install pnpm
        run: make install-pnpm
      - name: Build artifacts
        run: make all
      - name: Check for changes
        run: git diff --exit-code
