name: ci main
# continuous integration on push to main and release branches

on:
  push:
    branches:
      - main
      - release/**

permissions:
  contents: read
  pull-requests: read

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
  go-tests:
    uses: ./.github/workflows/gotest.yml
  go-lint:
    uses: ./.github/workflows/golangci-lint.yml
  sol-tests:
      uses: ./.github/workflows/soltest.yml
  cli-install:
    uses: ./.github/workflows/cliinstall.yml
  cli-command:
    uses: ./.github/workflows/clicommand.yml
  release-snapshot:
    uses: ./.github/workflows/release-snapshot.yml
    needs: [pre-commit, go-tests, go-lint, sol-tests]
    secrets: inherit
  e2e:
    uses: ./.github/workflows/e2etest.yml
    needs: [release-snapshot]
