name: go tests
# Run this separately from pre-commit for nice visual coverage.

on:
  workflow_call:

jobs:
  unit_tests:
    runs-on: namespace-profile-default
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'v1.24'

      - uses: ./.github/actions/setup-foundry
        with:
          docker: "true"

      # TODO(corver): add coverage
      - name: Run all tests (with race)
        run: go test -timeout=5m -race ./...

      - name: Run halo/app tests (without race)
        run: go test -timeout=5m github.com/omni-network/omni/halo/app
