name: pre-commit hooks

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      # Skip a few hooks: Golangci-lint and go-tests have their own actions. Allow lints against main commits.
      SKIP: golangci-lint,run-go-tests,no-commit-to-branch,run-forge-tests,run-forge-fmt
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
